name = "TCA"
version = "0.2.0"
keywords = ["math", "algebra", "temporal", "quantum"]
defaultTargets = ["TemporalClosureAlgebra", "QuantumAsTCA", "SpacetimeAsTCA", "InformationParadox"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
linter.style.whitespace = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.1"

[[lean_lib]]
name = "TemporalClosureAlgebra"
srcDir = "spec"

[[lean_lib]]
name = "QuantumAsTCA"
srcDir = "spec"

[[lean_lib]]
name = "SpacetimeAsTCA"
srcDir = "spec"

[[lean_lib]]
name = "InformationParadox"
srcDir = "spec"
