-- SPDX-License-Identifier: BSD-2-Clause
import TemporalClosureAlgebra
import QuantumAsTCA
import SpacetimeAsTCA
import InformationParadox
import EquityPremium
import SubstrateConfusions
import EconomicConfusions
import BiologicalConfusions

-- TCA
#print axioms TCA.Theorem_Irreversibility_of_Closure
#print axioms TCA.Theorem_Coupling
#print axioms TCA.Theorem_Default_as_Limit
#print axioms TCA.TSF_Axiom_2_as_TCA_Theorem

-- Quantum v0.2
#print axioms QuantumAsTCA.Theorem_Unitary_Evolution_Has_No_Closures
#print axioms QuantumAsTCA.Theorem_PVM_Posts_Both_Sides
#print axioms QuantumAsTCA.Theorem_PVM_Satisfies_DoubleEntry
#print axioms QuantumAsTCA.Theorem_Measurement_Ledger_Is_Monotone
#print axioms QuantumAsTCA.Theorem_Measurement_Is_Irreversible
#print axioms QuantumAsTCA.Theorem_Entanglement_Is_Shared_Preparation_Coupling
#print axioms QuantumAsTCA.Corollary_Measurement_And_Entanglement

-- Resolved (were deferred, now fully proved)
#print axioms TCA.Theorem_Finite_Externalization
#print axioms TCA.synchronous_closure_collapse

-- Spacetime
#print axioms SpacetimeAsTCA.Theorem_Geodesic_Incompleteness_Is_Default
#print axioms SpacetimeAsTCA.Theorem_Default_Persists
#print axioms SpacetimeAsTCA.Theorem_Completed_Geodesic_Irreversible
#print axioms SpacetimeAsTCA.Theorem_Singularity_Is_Permanent_Default
#print axioms SpacetimeAsTCA.Theorem_BlackHole_Events_Are_Coupled

-- Information Paradox
#print axioms InformationParadox.IP1_monotone_time_per_substrate
#print axioms InformationParadox.IP2_spacetime_open_independent_of_quantum
#print axioms InformationParadox.IP3_spacetime_information_persists
#print axioms InformationParadox.IP4_information_never_lost
#print axioms InformationParadox.evaporation_dichotomy

-- Equity Premium
#print axioms EquityPremium.EP1_bond_closes
#print axioms EquityPremium.EP2_equity_stays_open
#print axioms EquityPremium.EP3_bond_settlement_irreversible
#print axioms EquityPremium.EP4_equity_structural_default
#print axioms EquityPremium.EP5_substrates_independent

-- Substrate Confusions
#print axioms SubstrateConfusions.substrates_independent
#print axioms SubstrateConfusions.cross_substrate_independence
#print axioms SubstrateConfusions.dichotomy
#print axioms SubstrateConfusions.measurement_problem_dissolved
#print axioms SubstrateConfusions.cosmological_constant_dissolved
#print axioms SubstrateConfusions.baryon_asymmetry_is_open_items
#print axioms SubstrateConfusions.dark_matter_is_substrate_asymmetry
#print axioms SubstrateConfusions.wave_particle_two_substrates
#print axioms SubstrateConfusions.hierarchy_is_capacity_ratio
#print axioms SubstrateConfusions.zeno_is_rapid_closure

-- Economic Confusions
#print axioms EconomicConfusions.phillips_breakdown
#print axioms EconomicConfusions.forward_premium_dissolved
#print axioms EconomicConfusions.dividend_puzzle_dissolved
#print axioms EconomicConfusions.liquidity_is_closure_speed
#print axioms EconomicConfusions.credit_spread_dissolved
#print axioms EconomicConfusions.peso_problem_dissolved
#print axioms EconomicConfusions.gibson_paradox_dissolved
#print axioms EconomicConfusions.economic_substrates_independent

-- Biological Confusions
#print axioms BiologicalConfusions.aging_is_open_item_accumulation
#print axioms BiologicalConfusions.repair_is_irreversible
#print axioms BiologicalConfusions.microbiome_is_cross_substrate_coupling
#print axioms BiologicalConfusions.dysbiosis_is_broken_crosslink
#print axioms BiologicalConfusions.cancer_is_checkpoint_failure
#print axioms BiologicalConfusions.normal_replication_closes
#print axioms BiologicalConfusions.autoimmunity_is_misdirected_closure
#print axioms BiologicalConfusions.resistance_is_kill_default
#print axioms BiologicalConfusions.resistance_coupling
#print axioms BiologicalConfusions.biological_substrates_independent
